on:
  push:
    branches:
      - develop
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker compose up -d
          docker compose exec website composer install
          docker compose exec website php bin/console doctrine:database:create --env=test
          docker compose exec website php bin/console doctrine:schema:update --env=test --force
          docker compose exec website php bin/phpunit

  merge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd charline-royer-inventaire && git pull"
      - run: ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }} "cd charline-royer-inventaire && docker compose up -d --build --force-recreate"
