on: [push]
name: Build and test
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
     
      - run: |
          docker compose up -d
          docker compose exec website composer install
          docker compose exec website php bin/phpunit
  